	com.jufengniao.news.entity.News n = new com.jufengniao.news.entity.News();
			n.setContent(news.getContent());
			n.setSources(news.getUrl());
			n.setTitle(news.getTitle());
			n.setCreateTime(news.getDate());
			n.setPark(parkService.get(new Long(1)));
			n.setMenu(menuService.get(new Long(85)));
			n.setTop(new Long(0));
			n.setViewsNumber(new Long(0));
			NewsFilter filter = new NewsFilter();
			newsService.save(n);
